### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by renchap** [doctor-g/ThunderstoneQuestRandomizer#11]
During the last Kickstarter the game has been offered in french & german for the first time.
According to the progress, I expect those localized versions will be delivered near the end of the year.

It would be great to be able to choose your language in the randomizer, switching both the UI (app) and content (card names) to the user's locale.

I do not know Flutter but I assume there are I18n libraries which should do the job for the UI.

For the cards, a change in the YAML to a multi-values `TranslatedNames` property is probably the easiest, like this:
```yml
- Quest: Bandits of Black Rock
  TranslatedName:
    fr: Bandits de Black Rock
  Sets:
  - Champion
  Heroes:
  - Name: Edlin
    TranslatedName:
      fr: Edlin
    Keywords: [ Human, Fighter, Hero ]
    Combo: [ Weapon ]
  Marketplace:
  - Name: Scionic Annals
    TranslatedName:
      fr: Annales Scioniques
    Keywords: [ Magic, Item ]
    Combo: [ Spell ]
```
And then in the UI you use the translation if available, with a fallback to the english name.

Would you be open to this? I can handle the french translation (I am doing some proof-reading for it).
